baseURL = 'https://fusion-dancing.eu/'
languageCode = 'en'
title = 'Fusion Dancing in Europe'
contentDir = "content"
timeZone = "Etc/UTC"

[outputs]
home = ["HTML", "RSS", "calendar"]
section = ["HTML", "RSS", "calendar"]

[security]
enableInlineShortcodes = true
